# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'definir_ascergrqZu.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_definir_asce(object):
    def setupUi(self, definir_asce):
        if not definir_asce.objectName():
            definir_asce.setObjectName(u"definir_asce")
        definir_asce.resize(354, 526)
        self.groupBox = QGroupBox(definir_asce)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 331, 131))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 171, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 60, 171, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 90, 151, 16))
        self.def_max_asce = QLineEdit(self.groupBox)
        self.def_max_asce.setObjectName(u"def_max_asce")
        self.def_max_asce.setGeometry(QRect(200, 30, 101, 22))
        self.def_max_asce.setReadOnly(True)
        self.def_ultima_asce = QLineEdit(self.groupBox)
        self.def_ultima_asce.setObjectName(u"def_ultima_asce")
        self.def_ultima_asce.setGeometry(QRect(200, 60, 101, 22))
        self.def_ultima_asce.setReadOnly(True)
        self.def_fluencia_asce = QLineEdit(self.groupBox)
        self.def_fluencia_asce.setObjectName(u"def_fluencia_asce")
        self.def_fluencia_asce.setGeometry(QRect(200, 90, 101, 22))
        self.def_fluencia_asce.setReadOnly(True)
        self.groupBox_2 = QGroupBox(definir_asce)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 150, 331, 161))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 30, 121, 16))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 60, 121, 16))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 90, 111, 16))
        self.long_viga_asce = QLineEdit(self.groupBox_2)
        self.long_viga_asce.setObjectName(u"long_viga_asce")
        self.long_viga_asce.setGeometry(QRect(200, 30, 81, 22))
        self.coef_viga_asce = QLineEdit(self.groupBox_2)
        self.coef_viga_asce.setObjectName(u"coef_viga_asce")
        self.coef_viga_asce.setGeometry(QRect(200, 60, 81, 22))
        self.cortante_viga_asce = QLineEdit(self.groupBox_2)
        self.cortante_viga_asce.setObjectName(u"cortante_viga_asce")
        self.cortante_viga_asce.setGeometry(QRect(200, 90, 81, 22))
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 120, 91, 16))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 30, 31, 16))
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(290, 90, 31, 16))
        self.condicion_viga_asce = QComboBox(self.groupBox_2)
        self.condicion_viga_asce.addItem("")
        self.condicion_viga_asce.addItem("")
        self.condicion_viga_asce.setObjectName(u"condicion_viga_asce")
        self.condicion_viga_asce.setGeometry(QRect(200, 120, 81, 22))
        self.btn_cancelar_asce = QPushButton(definir_asce)
        self.btn_cancelar_asce.setObjectName(u"btn_cancelar_asce")
        self.btn_cancelar_asce.setGeometry(QRect(180, 490, 75, 24))
        self.btn_guardar_asce = QPushButton(definir_asce)
        self.btn_guardar_asce.setObjectName(u"btn_guardar_asce")
        self.btn_guardar_asce.setGeometry(QRect(100, 490, 75, 24))
        self.groupBox_3 = QGroupBox(definir_asce)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 320, 331, 161))
        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 30, 121, 16))
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 60, 121, 16))
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 90, 111, 16))
        self.long_columna_asce = QLineEdit(self.groupBox_3)
        self.long_columna_asce.setObjectName(u"long_columna_asce")
        self.long_columna_asce.setGeometry(QRect(200, 30, 81, 22))
        self.axial_columna_asce = QLineEdit(self.groupBox_3)
        self.axial_columna_asce.setObjectName(u"axial_columna_asce")
        self.axial_columna_asce.setGeometry(QRect(200, 60, 81, 22))
        self.cortante_columna_asce = QLineEdit(self.groupBox_3)
        self.cortante_columna_asce.setObjectName(u"cortante_columna_asce")
        self.cortante_columna_asce.setGeometry(QRect(200, 90, 81, 22))
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 120, 91, 16))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(290, 30, 31, 16))
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(290, 90, 31, 16))
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(290, 60, 31, 16))
        self.condicion_columna_asce = QComboBox(self.groupBox_3)
        self.condicion_columna_asce.addItem("")
        self.condicion_columna_asce.addItem("")
        self.condicion_columna_asce.setObjectName(u"condicion_columna_asce")
        self.condicion_columna_asce.setGeometry(QRect(200, 120, 81, 22))

        self.retranslateUi(definir_asce)

        QMetaObject.connectSlotsByName(definir_asce)
    # setupUi

    def retranslateUi(self, definir_asce):
        definir_asce.setWindowTitle(QCoreApplication.translate("definir_asce", u"Definir Par\u00e1metros ASCE", None))
        self.groupBox.setTitle(QCoreApplication.translate("definir_asce", u"Informaci\u00f3n General", None))
        self.label.setText(QCoreApplication.translate("definir_asce", u"Def. a compresi\u00f3n, \u03b5co", None))
        self.label_3.setText(QCoreApplication.translate("definir_asce", u"Def. \u00faltima del hormig\u00f3n, 2*\u03b5co", None))
        self.label_4.setText(QCoreApplication.translate("definir_asce", u"Def. de fluencia del acero, \u03b5y", None))
        self.def_max_asce.setText(QCoreApplication.translate("definir_asce", u"0.002", None))
        self.def_ultima_asce.setText(QCoreApplication.translate("definir_asce", u"0.0038", None))
        self.def_fluencia_asce.setText(QCoreApplication.translate("definir_asce", u"0.0021", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("definir_asce", u"Viga", None))
        self.label_13.setText(QCoreApplication.translate("definir_asce", u"Longitud Total, L", None))
        self.label_15.setText(QCoreApplication.translate("definir_asce", u"Coeficiente", None))
        self.label_16.setText(QCoreApplication.translate("definir_asce", u"Cortante, V", None))
        self.long_viga_asce.setText(QCoreApplication.translate("definir_asce", u"6", None))
        self.coef_viga_asce.setText(QCoreApplication.translate("definir_asce", u"05", None))
        self.cortante_viga_asce.setText(QCoreApplication.translate("definir_asce", u"2000", None))
        self.label_19.setText(QCoreApplication.translate("definir_asce", u"Condici\u00f3n", None))
        self.label_14.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_17.setText(QCoreApplication.translate("definir_asce", u"kg", None))
        self.condicion_viga_asce.setItemText(0, QCoreApplication.translate("definir_asce", u"Flexi\u00f3n", None))
        self.condicion_viga_asce.setItemText(1, QCoreApplication.translate("definir_asce", u"Corte", None))

        self.btn_cancelar_asce.setText(QCoreApplication.translate("definir_asce", u"Cancelar", None))
        self.btn_guardar_asce.setText(QCoreApplication.translate("definir_asce", u"Guardar", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("definir_asce", u"Columna", None))
        self.label_18.setText(QCoreApplication.translate("definir_asce", u"Longitud Total, L", None))
        self.label_20.setText(QCoreApplication.translate("definir_asce", u"Carga Axial, P", None))
        self.label_21.setText(QCoreApplication.translate("definir_asce", u"Cortante, V", None))
        self.long_columna_asce.setText(QCoreApplication.translate("definir_asce", u"6", None))
        self.axial_columna_asce.setText(QCoreApplication.translate("definir_asce", u"20000", None))
        self.cortante_columna_asce.setText(QCoreApplication.translate("definir_asce", u"6000", None))
        self.label_22.setText(QCoreApplication.translate("definir_asce", u"Condici\u00f3n", None))
        self.label_23.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_24.setText(QCoreApplication.translate("definir_asce", u"kg", None))
        self.label_25.setText(QCoreApplication.translate("definir_asce", u"kg", None))
        self.condicion_columna_asce.setItemText(0, QCoreApplication.translate("definir_asce", u"Flexi\u00f3n", None))
        self.condicion_columna_asce.setItemText(1, QCoreApplication.translate("definir_asce", u"Corte", None))

    # retranslateUi

