# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'definir_asceWFcLli.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_definir_asce(object):
    def setupUi(self, definir_asce):
        if not definir_asce.objectName():
            definir_asce.setObjectName(u"definir_asce")
        definir_asce.resize(1037, 689)
        self.groupBox = QGroupBox(definir_asce)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 5, 331, 121))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 171, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 60, 171, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 90, 151, 16))
        self.def_max_asce = QLineEdit(self.groupBox)
        self.def_max_asce.setObjectName(u"def_max_asce")
        self.def_max_asce.setEnabled(False)
        self.def_max_asce.setGeometry(QRect(200, 30, 101, 22))
        self.def_max_asce.setReadOnly(True)
        self.def_ultima_asce = QLineEdit(self.groupBox)
        self.def_ultima_asce.setObjectName(u"def_ultima_asce")
        self.def_ultima_asce.setEnabled(False)
        self.def_ultima_asce.setGeometry(QRect(200, 60, 101, 22))
        self.def_ultima_asce.setReadOnly(True)
        self.def_fluencia_asce = QLineEdit(self.groupBox)
        self.def_fluencia_asce.setObjectName(u"def_fluencia_asce")
        self.def_fluencia_asce.setEnabled(False)
        self.def_fluencia_asce.setGeometry(QRect(200, 90, 101, 22))
        self.def_fluencia_asce.setReadOnly(True)
        self.groupBox_2 = QGroupBox(definir_asce)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 130, 331, 131))
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(290, 30, 31, 16))
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 30, 101, 16))
        self.btn_calcular_rotacion = QPushButton(self.groupBox_2)
        self.btn_calcular_rotacion.setObjectName(u"btn_calcular_rotacion")
        self.btn_calcular_rotacion.setGeometry(QRect(130, 95, 75, 24))
        self.axial_columna_asce = QLineEdit(self.groupBox_2)
        self.axial_columna_asce.setObjectName(u"axial_columna_asce")
        self.axial_columna_asce.setEnabled(False)
        self.axial_columna_asce.setGeometry(QRect(200, 30, 81, 22))
        self.axial_columna_asce.setReadOnly(True)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 60, 101, 16))
        self.corte_viga_asce = QLineEdit(self.groupBox_2)
        self.corte_viga_asce.setObjectName(u"corte_viga_asce")
        self.corte_viga_asce.setGeometry(QRect(200, 60, 81, 22))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(290, 60, 31, 16))
        self.groupBox_3 = QGroupBox(definir_asce)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 300, 331, 381))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 30, 121, 16))
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 30, 31, 16))
        self.long_viga_asce = QLineEdit(self.groupBox_3)
        self.long_viga_asce.setObjectName(u"long_viga_asce")
        self.long_viga_asce.setGeometry(QRect(200, 30, 81, 22))
        self.btn_calcular_curvatura = QPushButton(self.groupBox_3)
        self.btn_calcular_curvatura.setObjectName(u"btn_calcular_curvatura")
        self.btn_calcular_curvatura.setGeometry(QRect(130, 65, 75, 24))
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 100, 311, 271))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 30, 121, 16))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(260, 30, 31, 16))
        self.rigidez_asce = QLineEdit(self.groupBox_4)
        self.rigidez_asce.setObjectName(u"rigidez_asce")
        self.rigidez_asce.setGeometry(QRect(170, 30, 81, 22))
        self.rigidez_asce.setReadOnly(True)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 60, 121, 16))
        self.m_fluencia_asce = QLineEdit(self.groupBox_4)
        self.m_fluencia_asce.setObjectName(u"m_fluencia_asce")
        self.m_fluencia_asce.setGeometry(QRect(170, 60, 81, 22))
        self.m_fluencia_asce.setReadOnly(True)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 60, 31, 16))
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 90, 31, 16))
        self.curv_fluencia_asce = QLineEdit(self.groupBox_4)
        self.curv_fluencia_asce.setObjectName(u"curv_fluencia_asce")
        self.curv_fluencia_asce.setGeometry(QRect(170, 90, 81, 22))
        self.curv_fluencia_asce.setReadOnly(True)
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 90, 121, 16))
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(260, 150, 31, 16))
        self.label_26 = QLabel(self.groupBox_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 150, 121, 16))
        self.label_27 = QLabel(self.groupBox_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(260, 120, 31, 16))
        self.m_maximo_asce = QLineEdit(self.groupBox_4)
        self.m_maximo_asce.setObjectName(u"m_maximo_asce")
        self.m_maximo_asce.setGeometry(QRect(170, 120, 81, 22))
        self.m_maximo_asce.setReadOnly(True)
        self.label_28 = QLabel(self.groupBox_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 120, 121, 16))
        self.curv_m_max_asce = QLineEdit(self.groupBox_4)
        self.curv_m_max_asce.setObjectName(u"curv_m_max_asce")
        self.curv_m_max_asce.setGeometry(QRect(170, 150, 81, 22))
        self.curv_m_max_asce.setReadOnly(True)
        self.m_ultimo_asce = QLineEdit(self.groupBox_4)
        self.m_ultimo_asce.setObjectName(u"m_ultimo_asce")
        self.m_ultimo_asce.setGeometry(QRect(170, 180, 81, 22))
        self.m_ultimo_asce.setReadOnly(True)
        self.curv_ultima_asce = QLineEdit(self.groupBox_4)
        self.curv_ultima_asce.setObjectName(u"curv_ultima_asce")
        self.curv_ultima_asce.setGeometry(QRect(170, 210, 81, 22))
        self.curv_ultima_asce.setReadOnly(True)
        self.label_29 = QLabel(self.groupBox_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 180, 121, 16))
        self.label_30 = QLabel(self.groupBox_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 210, 121, 16))
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(260, 180, 31, 16))
        self.label_32 = QLabel(self.groupBox_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(260, 210, 31, 16))
        self.ductilidad_asce = QLineEdit(self.groupBox_4)
        self.ductilidad_asce.setObjectName(u"ductilidad_asce")
        self.ductilidad_asce.setGeometry(QRect(170, 240, 81, 22))
        self.ductilidad_asce.setReadOnly(True)
        self.label_33 = QLabel(self.groupBox_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(260, 240, 31, 16))
        self.label_34 = QLabel(self.groupBox_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 240, 121, 16))
        self.cuadricula_ASCE = QWidget(definir_asce)
        self.cuadricula_ASCE.setObjectName(u"cuadricula_ASCE")
        self.cuadricula_ASCE.setGeometry(QRect(360, 12, 671, 671))
        self.checkBox_curvatura = QCheckBox(definir_asce)
        self.checkBox_curvatura.setObjectName(u"checkBox_curvatura")
        self.checkBox_curvatura.setGeometry(QRect(10, 270, 141, 20))

        self.retranslateUi(definir_asce)

        QMetaObject.connectSlotsByName(definir_asce)
    # setupUi

    def retranslateUi(self, definir_asce):
        definir_asce.setWindowTitle(QCoreApplication.translate("definir_asce", u"Definir Par\u00e1metros ASCE", None))
        self.groupBox.setTitle(QCoreApplication.translate("definir_asce", u"Informaci\u00f3n General", None))
        self.label.setText(QCoreApplication.translate("definir_asce", u"Def. a compresi\u00f3n", None))
        self.label_3.setText(QCoreApplication.translate("definir_asce", u"Def. \u00faltima del hormig\u00f3n", None))
        self.label_4.setText(QCoreApplication.translate("definir_asce", u"Def. de fluencia del acero", None))
        self.def_max_asce.setText(QCoreApplication.translate("definir_asce", u"0.002", None))
        self.def_ultima_asce.setText(QCoreApplication.translate("definir_asce", u"0.0038", None))
        self.def_fluencia_asce.setText(QCoreApplication.translate("definir_asce", u"0.0021", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("definir_asce", u"Momento - Rotaci\u00f3n", None))
        self.label_25.setText(QCoreApplication.translate("definir_asce", u"kg", None))
        self.label_20.setText(QCoreApplication.translate("definir_asce", u"Carga Axial, P", None))
        self.btn_calcular_rotacion.setText(QCoreApplication.translate("definir_asce", u"Mostrar", None))
        self.axial_columna_asce.setText(QCoreApplication.translate("definir_asce", u"3000", None))
        self.label_15.setText(QCoreApplication.translate("definir_asce", u"Cortante, V", None))
        self.corte_viga_asce.setText(QCoreApplication.translate("definir_asce", u"6", None))
        self.label_16.setText(QCoreApplication.translate("definir_asce", u"kg", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("definir_asce", u"Requisito de entrada", None))
        self.label_13.setText(QCoreApplication.translate("definir_asce", u"Longitud Total, L", None))
        self.label_14.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.long_viga_asce.setText(QCoreApplication.translate("definir_asce", u"6", None))
        self.btn_calcular_curvatura.setText(QCoreApplication.translate("definir_asce", u"Mostrar", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("definir_asce", u"Par\u00e1metros Caracter\u00edsticos", None))
        self.label_17.setText(QCoreApplication.translate("definir_asce", u"Rigidez Inicial", None))
        self.label_18.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.rigidez_asce.setText("")
        self.label_19.setText(QCoreApplication.translate("definir_asce", u"Momento de Fluencia", None))
        self.m_fluencia_asce.setText("")
        self.label_21.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_22.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.curv_fluencia_asce.setText("")
        self.label_23.setText(QCoreApplication.translate("definir_asce", u"Curvatura de Fluencia", None))
        self.label_24.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_26.setText(QCoreApplication.translate("definir_asce", u"Curvatura (Mmax)", None))
        self.label_27.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.m_maximo_asce.setText("")
        self.label_28.setText(QCoreApplication.translate("definir_asce", u"Momento M\u00e1ximo", None))
        self.curv_m_max_asce.setText("")
        self.m_ultimo_asce.setText("")
        self.curv_ultima_asce.setText("")
        self.label_29.setText(QCoreApplication.translate("definir_asce", u"Momento \u00daltimo", None))
        self.label_30.setText(QCoreApplication.translate("definir_asce", u"Curvatura \u00daltima", None))
        self.label_31.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_32.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.ductilidad_asce.setText("")
        self.label_33.setText(QCoreApplication.translate("definir_asce", u"m", None))
        self.label_34.setText(QCoreApplication.translate("definir_asce", u"Ductilidad", None))
        self.checkBox_curvatura.setText(QCoreApplication.translate("definir_asce", u"Momento - Curvatura", None))
    # retranslateUi

