# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventana_principal - copiamEmPIu.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QStackedWidget, QStatusBar,
    QToolBar, QVBoxLayout, QWidget)

import sys, os
def resource_path(relative_path: str) -> str:
    """
    Devuelve la ruta absoluta al recurso, válida tanto en desarrollo
    como en el ejecutable generado con PyInstaller.
    """
    base_path = getattr(sys, "_MEIPASS", os.path.abspath("."))
    return os.path.join(base_path, relative_path)

class Ui_ventana_principal(object):
    def setupUi(self, ventana_principal):
        if not ventana_principal.objectName():
            ventana_principal.setObjectName(u"ventana_principal")
        ventana_principal.resize(800, 595)
        ventana_principal.setMinimumSize(QSize(800, 595))
        self.actionAbrir = QAction(ventana_principal)
        self.actionAbrir.setObjectName(u"actionAbrir")
        icon = QIcon()
        icon.addFile(resource_path("New folder/abrir.png"), QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbrir.setIcon(icon)
        self.actionNuevo = QAction(ventana_principal)
        self.actionNuevo.setObjectName(u"actionNuevo")
        icon1 = QIcon()
        icon1.addFile(resource_path("New folder/nuevo.png"), QSize(), QIcon.Normal, QIcon.Off)
        self.actionNuevo.setIcon(icon1)
        self.actionGuardar = QAction(ventana_principal)
        self.actionGuardar.setObjectName(u"actionGuardar")
        icon2 = QIcon()
        icon2.addFile(resource_path("New folder/guardar.png"), QSize(), QIcon.Normal, QIcon.Off)
        self.actionGuardar.setIcon(icon2)
        self.actionGuardar_como = QAction(ventana_principal)
        self.actionGuardar_como.setObjectName(u"actionGuardar_como")
        icon3 = QIcon()
        icon3.addFile(resource_path("New folder/guardarcomo.png"), QSize(), QIcon.Normal, QIcon.Off)
        self.actionGuardar_como.setIcon(icon3)
        self.actionSalir = QAction(ventana_principal)
        self.actionSalir.setObjectName(u"actionSalir")
        icon4 = QIcon()
        icon4.addFile(resource_path("New folder/salir.png"), QSize(), QIcon.Normal, QIcon.Off)
        self.actionSalir.setIcon(icon4)
        self.actionSeccion = QAction(ventana_principal)
        self.actionSeccion.setObjectName(u"actionSeccion")
        self.actionParametros_ASCE = QAction(ventana_principal)
        self.actionParametros_ASCE.setObjectName(u"actionParametros_ASCE")
        self.actionCapas_de_Fibras = QAction(ventana_principal)
        self.actionCapas_de_Fibras.setObjectName(u"actionCapas_de_Fibras")
        self.actionDiagrama_de_iteracion = QAction(ventana_principal)
        self.actionDiagrama_de_iteracion.setObjectName(u"actionDiagrama_de_iteracion")
        self.actionDiagrama_M_C = QAction(ventana_principal)
        self.actionDiagrama_M_C.setObjectName(u"actionDiagrama_M_C")
        self.actionCapas_de_Fibras_2 = QAction(ventana_principal)
        self.actionCapas_de_Fibras_2.setObjectName(u"actionCapas_de_Fibras_2")
        self.actionCapas_de_Fibras_2.setCheckable(True)
        self.actionExportar_PDF = QAction(ventana_principal)
        self.actionExportar_PDF.setObjectName(u"actionExportar_PDF")
        self.actionDocumentaci_n = QAction(ventana_principal)
        self.actionDocumentaci_n.setObjectName(u"actionDocumentaci_n")
        self.actionHormig_n_2 = QAction(ventana_principal)
        self.actionHormig_n_2.setObjectName(u"actionHormig_n_2")
        self.actionAcero_2 = QAction(ventana_principal)
        self.actionAcero_2.setObjectName(u"actionAcero_2")
        self.actionProyecto = QAction(ventana_principal)
        self.actionProyecto.setObjectName(u"actionProyecto")
        self.actionExportar_Word = QAction(ventana_principal)
        self.actionExportar_Word.setObjectName(u"actionExportar_Word")
        self.centralwidget = QWidget(ventana_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_5 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.frame = QFrame(self.frame_2)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(300, 0))
        self.frame.setMaximumSize(QSize(300, 16777215))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget_proyecto = QStackedWidget(self.frame)
        self.stackedWidget_proyecto.setObjectName(u"stackedWidget_proyecto")
        self.stackedWidget_proyecto.setMinimumSize(QSize(300, 0))
        self.stackedWidget_proyecto.setMaximumSize(QSize(300, 16777215))
        self.pg_definir_proyecto = QWidget()
        self.pg_definir_proyecto.setObjectName(u"pg_definir_proyecto")
        self.pg_definir_proyecto.setMinimumSize(QSize(298, 0))
        self.verticalLayout_7 = QVBoxLayout(self.pg_definir_proyecto)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.frame_10 = QFrame(self.pg_definir_proyecto)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setMinimumSize(QSize(0, 310))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.frame_10)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMaximumSize(QSize(16777215, 16))
        self.label_9.setStyleSheet(u"font: 700 9pt \"Segoe UI\";")

        self.verticalLayout_8.addWidget(self.label_9)

        self.groupBox = QGroupBox(self.frame_10)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(0, 111))
        self.groupBox.setMaximumSize(QSize(16777215, 111))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 71, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 50, 71, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 80, 71, 16))
        self.descripcion_proyecto = QLineEdit(self.groupBox)
        self.descripcion_proyecto.setObjectName(u"descripcion_proyecto")
        self.descripcion_proyecto.setGeometry(QRect(120, 20, 161, 22))
        self.descripcion_ingeniero = QLineEdit(self.groupBox)
        self.descripcion_ingeniero.setObjectName(u"descripcion_ingeniero")
        self.descripcion_ingeniero.setGeometry(QRect(120, 50, 161, 22))
        self.descripcion_seccion = QLineEdit(self.groupBox)
        self.descripcion_seccion.setObjectName(u"descripcion_seccion")
        self.descripcion_seccion.setGeometry(QRect(120, 80, 161, 22))
        self.descripcion_seccion.setReadOnly(False)

        self.verticalLayout_8.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.frame_10)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setMinimumSize(QSize(0, 81))
        self.groupBox_2.setMaximumSize(QSize(16777215, 81))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 20, 81, 16))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 50, 81, 16))
        self.proyecto_fc = QLineEdit(self.groupBox_2)
        self.proyecto_fc.setObjectName(u"proyecto_fc")
        self.proyecto_fc.setGeometry(QRect(120, 20, 111, 22))
        self.proyecto_fc.setReadOnly(True)
        self.proyecto_fy = QLineEdit(self.groupBox_2)
        self.proyecto_fy.setObjectName(u"proyecto_fy")
        self.proyecto_fy.setGeometry(QRect(120, 50, 111, 22))
        self.proyecto_fy.setReadOnly(True)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 20, 51, 16))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(240, 50, 51, 16))

        self.verticalLayout_8.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(self.frame_10)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.seccion_analisis = QComboBox(self.groupBox_3)
        self.seccion_analisis.addItem("")
        self.seccion_analisis.addItem("")
        self.seccion_analisis.setObjectName(u"seccion_analisis")
        self.seccion_analisis.setGeometry(QRect(120, 20, 111, 22))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 20, 81, 16))
        self.direccion_analisis = QComboBox(self.groupBox_3)
        self.direccion_analisis.addItem("")
        self.direccion_analisis.addItem("")
        self.direccion_analisis.setObjectName(u"direccion_analisis")
        self.direccion_analisis.setGeometry(QRect(120, 50, 111, 22))
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 50, 81, 16))

        self.verticalLayout_8.addWidget(self.groupBox_3)


        self.verticalLayout_7.addWidget(self.frame_10)

        self.frame_9 = QFrame(self.pg_definir_proyecto)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget = QStackedWidget(self.frame_9)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.pg_p_columna = QWidget()
        self.pg_p_columna.setObjectName(u"pg_p_columna")
        self.groupBox_5 = QGroupBox(self.pg_p_columna)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 10, 295, 111))
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 20, 81, 16))
        self.label_20 = QLabel(self.groupBox_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 50, 81, 16))
        self.columna_area_gruesa = QLineEdit(self.groupBox_5)
        self.columna_area_gruesa.setObjectName(u"columna_area_gruesa")
        self.columna_area_gruesa.setGeometry(QRect(120, 20, 111, 22))
        self.columna_area_gruesa.setReadOnly(True)
        self.columna_total_as = QLineEdit(self.groupBox_5)
        self.columna_total_as.setObjectName(u"columna_total_as")
        self.columna_total_as.setGeometry(QRect(120, 50, 111, 22))
        self.columna_total_as.setReadOnly(True)
        self.label_21 = QLabel(self.groupBox_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(240, 20, 51, 16))
        self.label_23 = QLabel(self.groupBox_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(240, 50, 51, 16))
        self.label_30 = QLabel(self.groupBox_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 80, 51, 16))
        self.label_31 = QLabel(self.groupBox_5)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(30, 80, 81, 16))
        self.columna_rho = QLineEdit(self.groupBox_5)
        self.columna_rho.setObjectName(u"columna_rho")
        self.columna_rho.setGeometry(QRect(120, 80, 111, 22))
        self.columna_rho.setReadOnly(True)
        self.stackedWidget.addWidget(self.pg_p_columna)
        self.pg_p_viga = QWidget()
        self.pg_p_viga.setObjectName(u"pg_p_viga")
        self.groupBox_4 = QGroupBox(self.pg_p_viga)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 10, 295, 171))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 20, 81, 16))
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 50, 81, 16))
        self.viga_area_gruesa = QLineEdit(self.groupBox_4)
        self.viga_area_gruesa.setObjectName(u"viga_area_gruesa")
        self.viga_area_gruesa.setGeometry(QRect(120, 20, 111, 22))
        self.viga_area_gruesa.setReadOnly(True)
        self.viga_as_sup = QLineEdit(self.groupBox_4)
        self.viga_as_sup.setObjectName(u"viga_as_sup")
        self.viga_as_sup.setGeometry(QRect(120, 50, 111, 22))
        self.viga_as_sup.setReadOnly(True)
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 20, 51, 16))
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(240, 50, 51, 16))
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 80, 81, 16))
        self.viga_as_inf = QLineEdit(self.groupBox_4)
        self.viga_as_inf.setObjectName(u"viga_as_inf")
        self.viga_as_inf.setGeometry(QRect(120, 80, 111, 22))
        self.viga_as_inf.setReadOnly(True)
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(240, 80, 51, 16))
        self.viga_rho_inf = QLineEdit(self.groupBox_4)
        self.viga_rho_inf.setObjectName(u"viga_rho_inf")
        self.viga_rho_inf.setGeometry(QRect(120, 140, 111, 22))
        self.viga_rho_inf.setReadOnly(True)
        self.viga_rho_sup = QLineEdit(self.groupBox_4)
        self.viga_rho_sup.setObjectName(u"viga_rho_sup")
        self.viga_rho_sup.setGeometry(QRect(120, 110, 111, 22))
        self.viga_rho_sup.setReadOnly(True)
        self.label_33 = QLabel(self.groupBox_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(240, 110, 51, 16))
        self.label_34 = QLabel(self.groupBox_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(30, 110, 81, 16))
        self.label_45 = QLabel(self.groupBox_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(30, 140, 81, 16))
        self.label_46 = QLabel(self.groupBox_4)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(240, 140, 51, 16))
        self.stackedWidget.addWidget(self.pg_p_viga)

        self.verticalLayout_9.addWidget(self.stackedWidget)


        self.verticalLayout_7.addWidget(self.frame_9)

        self.stackedWidget_proyecto.addWidget(self.pg_definir_proyecto)
        self.pg_definir_seccion = QWidget()
        self.pg_definir_seccion.setObjectName(u"pg_definir_seccion")
        self.verticalLayout_2 = QVBoxLayout(self.pg_definir_seccion)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.pg_definir_seccion)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setMinimumSize(QSize(0, 50))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1, 1, 111, 16))
        self.label_10.setStyleSheet(u"font: 700 9pt \"Segoe UI\";")
        self.texto_seccion = QLabel(self.frame_3)
        self.texto_seccion.setObjectName(u"texto_seccion")
        self.texto_seccion.setGeometry(QRect(100, 20, 101, 21))
        font = QFont()
        font.setBold(True)
        self.texto_seccion.setFont(font)
        self.texto_seccion.setTextFormat(Qt.AutoText)
        self.texto_seccion.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.frame_3)

        self.frame_4 = QFrame(self.pg_definir_seccion)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget_seccion = QStackedWidget(self.frame_4)
        self.stackedWidget_seccion.setObjectName(u"stackedWidget_seccion")
        self.stackedWidget_seccion.setMinimumSize(QSize(0, 0))
        self.pg_columna = QWidget()
        self.pg_columna.setObjectName(u"pg_columna")
        self.verticalLayout_4 = QVBoxLayout(self.pg_columna)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.frame_6 = QFrame(self.pg_columna)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.frame_6)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 277, 500))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(0, 500))
        self.groupBox_8 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 10, 255, 55))
        self.label_18 = QLabel(self.groupBox_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 20, 61, 16))
        self.disenar_columna_nombre = QLineEdit(self.groupBox_8)
        self.disenar_columna_nombre.setObjectName(u"disenar_columna_nombre")
        self.disenar_columna_nombre.setGeometry(QRect(140, 20, 101, 22))
        self.disenar_columna_nombre.setReadOnly(True)
        self.groupBox_10 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 70, 255, 85))
        self.label_24 = QLabel(self.groupBox_10)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 20, 61, 16))
        self.label_25 = QLabel(self.groupBox_10)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 50, 61, 16))
        self.label_26 = QLabel(self.groupBox_10)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(230, 20, 21, 16))
        self.label_27 = QLabel(self.groupBox_10)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(230, 50, 21, 16))
        self.disenar_columna_base = QLineEdit(self.groupBox_10)
        self.disenar_columna_base.setObjectName(u"disenar_columna_base")
        self.disenar_columna_base.setGeometry(QRect(140, 20, 81, 22))
        self.disenar_columna_altura = QLineEdit(self.groupBox_10)
        self.disenar_columna_altura.setObjectName(u"disenar_columna_altura")
        self.disenar_columna_altura.setGeometry(QRect(140, 50, 81, 22))
        self.groupBox_13 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 220, 255, 115))
        self.label_35 = QLabel(self.groupBox_13)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(30, 20, 101, 16))
        self.disenar_columna_varillasX_2 = QLineEdit(self.groupBox_13)
        self.disenar_columna_varillasX_2.setObjectName(u"disenar_columna_varillasX_2")
        self.disenar_columna_varillasX_2.setGeometry(QRect(140, 20, 81, 22))
        self.label_38 = QLabel(self.groupBox_13)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(30, 50, 101, 16))
        self.disenar_columna_varillasY_2 = QLineEdit(self.groupBox_13)
        self.disenar_columna_varillasY_2.setObjectName(u"disenar_columna_varillasY_2")
        self.disenar_columna_varillasY_2.setGeometry(QRect(140, 50, 81, 22))
        self.label_39 = QLabel(self.groupBox_13)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(30, 80, 101, 16))
        self.disenar_columna_diametro_longitudinal_2 = QLineEdit(self.groupBox_13)
        self.disenar_columna_diametro_longitudinal_2.setObjectName(u"disenar_columna_diametro_longitudinal_2")
        self.disenar_columna_diametro_longitudinal_2.setGeometry(QRect(140, 80, 81, 22))
        self.label_40 = QLabel(self.groupBox_13)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(230, 80, 21, 16))
        self.groupBox_11 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 160, 255, 55))
        self.label_28 = QLabel(self.groupBox_11)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(30, 20, 61, 16))
        self.label_29 = QLabel(self.groupBox_11)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(230, 20, 21, 16))
        self.disenar_columna_recubrimiento = QLineEdit(self.groupBox_11)
        self.disenar_columna_recubrimiento.setObjectName(u"disenar_columna_recubrimiento")
        self.disenar_columna_recubrimiento.setGeometry(QRect(140, 20, 81, 22))
        self.groupBox_14 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 340, 261, 145))
        self.label_36 = QLabel(self.groupBox_14)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(30, 20, 101, 16))
        self.disenar_columna_ramalesX = QLineEdit(self.groupBox_14)
        self.disenar_columna_ramalesX.setObjectName(u"disenar_columna_ramalesX")
        self.disenar_columna_ramalesX.setGeometry(QRect(140, 20, 81, 22))
        self.label_37 = QLabel(self.groupBox_14)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(30, 50, 101, 16))
        self.disenar_columna_ramalesY = QLineEdit(self.groupBox_14)
        self.disenar_columna_ramalesY.setObjectName(u"disenar_columna_ramalesY")
        self.disenar_columna_ramalesY.setGeometry(QRect(140, 50, 81, 22))
        self.label_41 = QLabel(self.groupBox_14)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(30, 80, 101, 16))
        self.disenar_columna_diametro_transversal = QLineEdit(self.groupBox_14)
        self.disenar_columna_diametro_transversal.setObjectName(u"disenar_columna_diametro_transversal")
        self.disenar_columna_diametro_transversal.setGeometry(QRect(140, 80, 81, 22))
        self.label_42 = QLabel(self.groupBox_14)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(230, 80, 21, 16))
        self.disenar_columna_espaciamiento = QLineEdit(self.groupBox_14)
        self.disenar_columna_espaciamiento.setObjectName(u"disenar_columna_espaciamiento")
        self.disenar_columna_espaciamiento.setGeometry(QRect(140, 110, 81, 22))
        self.label_43 = QLabel(self.groupBox_14)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(30, 110, 101, 16))
        self.label_44 = QLabel(self.groupBox_14)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(230, 110, 21, 16))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout_3.addWidget(self.scrollArea)


        self.verticalLayout_4.addWidget(self.frame_6)

        self.frame_5 = QFrame(self.pg_columna)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setMinimumSize(QSize(0, 25))
        self.frame_5.setMaximumSize(QSize(16777215, 100))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_calcular_columna = QPushButton(self.frame_5)
        self.btn_calcular_columna.setObjectName(u"btn_calcular_columna")
        self.btn_calcular_columna.setMaximumSize(QSize(16777215, 22))

        self.horizontalLayout_4.addWidget(self.btn_calcular_columna)


        self.verticalLayout_4.addWidget(self.frame_5)

        self.stackedWidget_seccion.addWidget(self.pg_columna)
        self.pg_viga = QWidget()
        self.pg_viga.setObjectName(u"pg_viga")
        self.verticalLayout_6 = QVBoxLayout(self.pg_viga)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.frame_7 = QFrame(self.pg_viga)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_2 = QScrollArea(self.frame_7)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 98, 500))
        self.scrollAreaWidgetContents_3.setMinimumSize(QSize(0, 500))
        self.groupBox_18 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 10, 255, 55))
        self.label_22 = QLabel(self.groupBox_18)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 20, 61, 16))
        self.disenar_viga_nombre = QLineEdit(self.groupBox_18)
        self.disenar_viga_nombre.setObjectName(u"disenar_viga_nombre")
        self.disenar_viga_nombre.setGeometry(QRect(140, 20, 101, 22))
        self.disenar_viga_nombre.setReadOnly(True)
        self.groupBox_19 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 70, 255, 85))
        self.label_58 = QLabel(self.groupBox_19)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(30, 20, 61, 16))
        self.label_59 = QLabel(self.groupBox_19)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(30, 50, 61, 16))
        self.label_60 = QLabel(self.groupBox_19)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(230, 20, 21, 16))
        self.label_61 = QLabel(self.groupBox_19)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(230, 50, 21, 16))
        self.disenar_viga_base = QLineEdit(self.groupBox_19)
        self.disenar_viga_base.setObjectName(u"disenar_viga_base")
        self.disenar_viga_base.setGeometry(QRect(140, 20, 81, 22))
        self.disenar_viga_altura = QLineEdit(self.groupBox_19)
        self.disenar_viga_altura.setObjectName(u"disenar_viga_altura")
        self.disenar_viga_altura.setGeometry(QRect(140, 50, 81, 22))
        self.groupBox_21 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(10, 160, 255, 55))
        self.label_66 = QLabel(self.groupBox_21)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(30, 20, 61, 16))
        self.label_67 = QLabel(self.groupBox_21)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(230, 20, 21, 16))
        self.disenar_viga_recubrimiento = QLineEdit(self.groupBox_21)
        self.disenar_viga_recubrimiento.setObjectName(u"disenar_viga_recubrimiento")
        self.disenar_viga_recubrimiento.setGeometry(QRect(140, 20, 81, 22))
        self.groupBox_20 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(10, 220, 255, 85))
        self.disenar_viga_varillas_inferior = QLineEdit(self.groupBox_20)
        self.disenar_viga_varillas_inferior.setObjectName(u"disenar_viga_varillas_inferior")
        self.disenar_viga_varillas_inferior.setGeometry(QRect(140, 20, 81, 22))
        self.label_62 = QLabel(self.groupBox_20)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(30, 20, 71, 16))
        self.label_63 = QLabel(self.groupBox_20)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(230, 50, 21, 16))
        self.disenar_viga_diametro_inferior = QLineEdit(self.groupBox_20)
        self.disenar_viga_diametro_inferior.setObjectName(u"disenar_viga_diametro_inferior")
        self.disenar_viga_diametro_inferior.setGeometry(QRect(140, 50, 81, 22))
        self.label_64 = QLabel(self.groupBox_20)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(30, 50, 71, 16))
        self.groupBox_22 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(10, 310, 255, 85))
        self.disenar_viga_varillas_superior = QLineEdit(self.groupBox_22)
        self.disenar_viga_varillas_superior.setObjectName(u"disenar_viga_varillas_superior")
        self.disenar_viga_varillas_superior.setGeometry(QRect(140, 20, 81, 22))
        self.label_70 = QLabel(self.groupBox_22)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(30, 20, 71, 16))
        self.label_71 = QLabel(self.groupBox_22)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(230, 50, 21, 16))
        self.disenar_viga_diametro_superior = QLineEdit(self.groupBox_22)
        self.disenar_viga_diametro_superior.setObjectName(u"disenar_viga_diametro_superior")
        self.disenar_viga_diametro_superior.setGeometry(QRect(140, 50, 81, 22))
        self.label_72 = QLabel(self.groupBox_22)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(30, 50, 71, 16))
        self.groupBox_23 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(10, 400, 255, 85))
        self.label_68 = QLabel(self.groupBox_23)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(30, 20, 71, 16))
        self.disenar_viga_diametro_transversal = QLineEdit(self.groupBox_23)
        self.disenar_viga_diametro_transversal.setObjectName(u"disenar_viga_diametro_transversal")
        self.disenar_viga_diametro_transversal.setGeometry(QRect(140, 20, 81, 22))
        self.label_69 = QLabel(self.groupBox_23)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(230, 20, 21, 16))
        self.label_73 = QLabel(self.groupBox_23)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(30, 50, 91, 16))
        self.disenar_viga_espaciamiento = QLineEdit(self.groupBox_23)
        self.disenar_viga_espaciamiento.setObjectName(u"disenar_viga_espaciamiento")
        self.disenar_viga_espaciamiento.setGeometry(QRect(140, 50, 81, 22))
        self.label_74 = QLabel(self.groupBox_23)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(230, 50, 21, 16))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)

        self.horizontalLayout.addWidget(self.scrollArea_2)


        self.verticalLayout_6.addWidget(self.frame_7)

        self.frame_8 = QFrame(self.pg_viga)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setMinimumSize(QSize(0, 25))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btn_calcular_viga = QPushButton(self.frame_8)
        self.btn_calcular_viga.setObjectName(u"btn_calcular_viga")
        self.btn_calcular_viga.setMaximumSize(QSize(16777215, 22))

        self.horizontalLayout_5.addWidget(self.btn_calcular_viga)


        self.verticalLayout_6.addWidget(self.frame_8)

        self.stackedWidget_seccion.addWidget(self.pg_viga)

        self.verticalLayout_3.addWidget(self.stackedWidget_seccion)


        self.verticalLayout_2.addWidget(self.frame_4)

        self.stackedWidget_proyecto.addWidget(self.pg_definir_seccion)

        self.verticalLayout.addWidget(self.stackedWidget_proyecto)


        self.horizontalLayout_2.addWidget(self.frame)

        self.cuadricula_seccion = QWidget(self.frame_2)
        self.cuadricula_seccion.setObjectName(u"cuadricula_seccion")

        self.horizontalLayout_2.addWidget(self.cuadricula_seccion)


        self.verticalLayout_5.addWidget(self.frame_2)

        ventana_principal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ventana_principal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuDefinir = QMenu(self.menubar)
        self.menuDefinir.setObjectName(u"menuDefinir")
        self.menuMaterial = QMenu(self.menuDefinir)
        self.menuMaterial.setObjectName(u"menuMaterial")
        self.menuMostrar = QMenu(self.menubar)
        self.menuMostrar.setObjectName(u"menuMostrar")
        self.menuReporte = QMenu(self.menubar)
        self.menuReporte.setObjectName(u"menuReporte")
        self.menuAyuda = QMenu(self.menubar)
        self.menuAyuda.setObjectName(u"menuAyuda")
        ventana_principal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(ventana_principal)
        self.statusbar.setObjectName(u"statusbar")
        ventana_principal.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(ventana_principal)
        self.toolBar.setObjectName(u"toolBar")
        ventana_principal.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuDefinir.menuAction())
        self.menubar.addAction(self.menuMostrar.menuAction())
        self.menubar.addAction(self.menuReporte.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_como)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuDefinir.addAction(self.menuMaterial.menuAction())
        self.menuDefinir.addAction(self.actionProyecto)
        self.menuDefinir.addAction(self.actionSeccion)
        self.menuDefinir.addSeparator()
        self.menuDefinir.addAction(self.actionParametros_ASCE)
        self.menuDefinir.addAction(self.actionCapas_de_Fibras)
        self.menuMaterial.addAction(self.actionHormig_n_2)
        self.menuMaterial.addAction(self.actionAcero_2)
        self.menuMostrar.addAction(self.actionDiagrama_de_iteracion)
        self.menuMostrar.addAction(self.actionDiagrama_M_C)
        self.menuMostrar.addAction(self.actionCapas_de_Fibras_2)
        self.menuReporte.addAction(self.actionExportar_PDF)
        self.menuReporte.addAction(self.actionExportar_Word)
        self.menuAyuda.addAction(self.actionDocumentaci_n)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbrir)
        self.toolBar.addAction(self.actionNuevo)
        self.toolBar.addAction(self.actionGuardar)
        self.toolBar.addAction(self.actionGuardar_como)

        self.retranslateUi(ventana_principal)

        self.stackedWidget_proyecto.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_seccion.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ventana_principal)
    # setupUi

    def retranslateUi(self, ventana_principal):
        ventana_principal.setWindowTitle(QCoreApplication.translate("ventana_principal", u"Diagrama M-C", None))
        self.actionAbrir.setText(QCoreApplication.translate("ventana_principal", u"Abrir", None))
        self.actionNuevo.setText(QCoreApplication.translate("ventana_principal", u"Nuevo", None))
        self.actionGuardar.setText(QCoreApplication.translate("ventana_principal", u"Guardar", None))
        self.actionGuardar_como.setText(QCoreApplication.translate("ventana_principal", u"Guardar como...", None))
        self.actionSalir.setText(QCoreApplication.translate("ventana_principal", u"Salir", None))
        self.actionSeccion.setText(QCoreApplication.translate("ventana_principal", u"Secci\u00f3n", None))
        self.actionParametros_ASCE.setText(QCoreApplication.translate("ventana_principal", u"Par\u00e1metros ASCE", None))
        self.actionCapas_de_Fibras.setText(QCoreApplication.translate("ventana_principal", u"Capas de Fibras", None))
        self.actionDiagrama_de_iteracion.setText(QCoreApplication.translate("ventana_principal", u"Diagrama de iteraci\u00f3n", None))
        self.actionDiagrama_M_C.setText(QCoreApplication.translate("ventana_principal", u"Diagrama M-C", None))
        self.actionCapas_de_Fibras_2.setText(QCoreApplication.translate("ventana_principal", u"Capas de Fibras", None))
        self.actionExportar_PDF.setText(QCoreApplication.translate("ventana_principal", u"Exportar PDF", None))
        self.actionDocumentaci_n.setText(QCoreApplication.translate("ventana_principal", u"Documentaci\u00f3n", None))
        self.actionHormig_n_2.setText(QCoreApplication.translate("ventana_principal", u"Hormig\u00f3n", None))
        self.actionAcero_2.setText(QCoreApplication.translate("ventana_principal", u"Acero", None))
        self.actionProyecto.setText(QCoreApplication.translate("ventana_principal", u"Proyecto", None))
        self.actionExportar_Word.setText(QCoreApplication.translate("ventana_principal", u"Exportar Word", None))
        self.label_9.setText(QCoreApplication.translate("ventana_principal", u"DEFINIR PROYECTO", None))
        self.groupBox.setTitle(QCoreApplication.translate("ventana_principal", u"Descripci\u00f3n", None))
        self.label.setText(QCoreApplication.translate("ventana_principal", u"Proyecto:", None))
        self.label_2.setText(QCoreApplication.translate("ventana_principal", u"Ingeniero:", None))
        self.label_3.setText(QCoreApplication.translate("ventana_principal", u"Secci\u00f3n:", None))
        self.descripcion_proyecto.setText(QCoreApplication.translate("ventana_principal", u"Nombre Proyecto", None))
        self.descripcion_ingeniero.setText(QCoreApplication.translate("ventana_principal", u"Luis Flor", None))
        self.descripcion_seccion.setText(QCoreApplication.translate("ventana_principal", u"C40X40", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("ventana_principal", u"Materiales", None))
        self.label_4.setText(QCoreApplication.translate("ventana_principal", u"Hormig\u00f3n, f'c:", None))
        self.label_5.setText(QCoreApplication.translate("ventana_principal", u"Acero, fy:", None))
        self.label_6.setText(QCoreApplication.translate("ventana_principal", u"kg/cm\u00b2", None))
        self.label_7.setText(QCoreApplication.translate("ventana_principal", u"kg/cm\u00b2", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("ventana_principal", u"Opci\u00f3n de An\u00e1lisis", None))
        self.seccion_analisis.setItemText(0, QCoreApplication.translate("ventana_principal", u"Columna", None))
        self.seccion_analisis.setItemText(1, QCoreApplication.translate("ventana_principal", u"Viga", None))

        self.label_8.setText(QCoreApplication.translate("ventana_principal", u"Secci\u00f3n:", None))
        self.direccion_analisis.setItemText(0, QCoreApplication.translate("ventana_principal", u"Direcci\u00f3n Y", None))
        self.direccion_analisis.setItemText(1, QCoreApplication.translate("ventana_principal", u"Direcci\u00f3n X", None))

        self.label_17.setText(QCoreApplication.translate("ventana_principal", u"Eje de An\u00e1lisis:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("ventana_principal", u"Propiedades", None))
        self.label_19.setText(QCoreApplication.translate("ventana_principal", u"\u00c1rea Gruesa:", None))
        self.label_20.setText(QCoreApplication.translate("ventana_principal", u"Total As:", None))
        self.label_21.setText(QCoreApplication.translate("ventana_principal", u"cm\u00b2", None))
        self.label_23.setText(QCoreApplication.translate("ventana_principal", u"cm\u00b2", None))
        self.label_30.setText(QCoreApplication.translate("ventana_principal", u"%", None))
        self.label_31.setText(QCoreApplication.translate("ventana_principal", u"Rho:", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("ventana_principal", u"Propiedades", None))
        self.label_11.setText(QCoreApplication.translate("ventana_principal", u"\u00c1rea Gruesa:", None))
        self.label_12.setText(QCoreApplication.translate("ventana_principal", u"As Superior:", None))
        self.label_13.setText(QCoreApplication.translate("ventana_principal", u"cm\u00b2", None))
        self.label_14.setText(QCoreApplication.translate("ventana_principal", u"cm\u00b2", None))
        self.label_16.setText(QCoreApplication.translate("ventana_principal", u"As Inferior:", None))
        self.label_15.setText(QCoreApplication.translate("ventana_principal", u"cm\u00b2", None))
        self.label_33.setText(QCoreApplication.translate("ventana_principal", u"%", None))
        self.label_34.setText(QCoreApplication.translate("ventana_principal", u"Rho Superior:", None))
        self.label_45.setText(QCoreApplication.translate("ventana_principal", u"Rho Inferior:", None))
        self.label_46.setText(QCoreApplication.translate("ventana_principal", u"%", None))
        self.label_10.setText(QCoreApplication.translate("ventana_principal", u"DEFINIR SECCI\u00d3N", None))
        self.texto_seccion.setText(QCoreApplication.translate("ventana_principal", u"COLUMNA", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("ventana_principal", u"Informaci\u00f3n General", None))
        self.label_18.setText(QCoreApplication.translate("ventana_principal", u"Nombre", None))
        self.disenar_columna_nombre.setText("")
        self.groupBox_10.setTitle(QCoreApplication.translate("ventana_principal", u"Geometr\u00eda", None))
        self.label_24.setText(QCoreApplication.translate("ventana_principal", u"Base (b)", None))
        self.label_25.setText(QCoreApplication.translate("ventana_principal", u"Altura (h)", None))
        self.label_26.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.label_27.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.disenar_columna_base.setText("")
        self.groupBox_13.setTitle(QCoreApplication.translate("ventana_principal", u"Refuerzo Longitudinal", None))
        self.label_35.setText(QCoreApplication.translate("ventana_principal", u"Capas (Eje X)", None))
        self.label_38.setText(QCoreApplication.translate("ventana_principal", u"Capas (Eje Y)", None))
        self.label_39.setText(QCoreApplication.translate("ventana_principal", u"Di\u00e1metro", None))
        self.label_40.setText(QCoreApplication.translate("ventana_principal", u"mm", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("ventana_principal", u"Recubrimiento", None))
        self.label_28.setText(QCoreApplication.translate("ventana_principal", u"Rec. Libre", None))
        self.label_29.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("ventana_principal", u"Refuerzo Transversal", None))
        self.label_36.setText(QCoreApplication.translate("ventana_principal", u"No. ramales (Eje X)", None))
        self.label_37.setText(QCoreApplication.translate("ventana_principal", u"No. ramales (Eje Y)", None))
        self.label_41.setText(QCoreApplication.translate("ventana_principal", u"Di\u00e1metro de varilla", None))
        self.label_42.setText(QCoreApplication.translate("ventana_principal", u"mm", None))
        self.disenar_columna_espaciamiento.setText("")
        self.label_43.setText(QCoreApplication.translate("ventana_principal", u"Espaciamiento", None))
        self.label_44.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.btn_calcular_columna.setText(QCoreApplication.translate("ventana_principal", u"Calcular", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("ventana_principal", u"Informaci\u00f3n General", None))
        self.label_22.setText(QCoreApplication.translate("ventana_principal", u"Nombre", None))
        self.disenar_viga_nombre.setText("")
        self.groupBox_19.setTitle(QCoreApplication.translate("ventana_principal", u"Geometr\u00eda", None))
        self.label_58.setText(QCoreApplication.translate("ventana_principal", u"Base (b)", None))
        self.label_59.setText(QCoreApplication.translate("ventana_principal", u"Altura (h)", None))
        self.label_60.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.label_61.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("ventana_principal", u"Recubrimiento", None))
        self.label_66.setText(QCoreApplication.translate("ventana_principal", u"Rec. Libre", None))
        self.label_67.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("ventana_principal", u"Refuerzo Longitudinal Inferior", None))
        self.label_62.setText(QCoreApplication.translate("ventana_principal", u"No. varillas", None))
        self.label_63.setText(QCoreApplication.translate("ventana_principal", u"mm", None))
        self.label_64.setText(QCoreApplication.translate("ventana_principal", u"Di\u00e1metro", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("ventana_principal", u"Refuerzo Longitudinal Superior", None))
        self.label_70.setText(QCoreApplication.translate("ventana_principal", u"No. varillas", None))
        self.label_71.setText(QCoreApplication.translate("ventana_principal", u"mm", None))
        self.label_72.setText(QCoreApplication.translate("ventana_principal", u"Di\u00e1metro", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("ventana_principal", u"Refuerzo Transversal", None))
        self.label_68.setText(QCoreApplication.translate("ventana_principal", u"Di\u00e1metro", None))
        self.label_69.setText(QCoreApplication.translate("ventana_principal", u"mm", None))
        self.label_73.setText(QCoreApplication.translate("ventana_principal", u"Espaciamiento", None))
        self.disenar_viga_espaciamiento.setText("")
        self.label_74.setText(QCoreApplication.translate("ventana_principal", u"cm", None))
        self.btn_calcular_viga.setText(QCoreApplication.translate("ventana_principal", u"Calcular", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("ventana_principal", u"Archivo", None))
        self.menuDefinir.setTitle(QCoreApplication.translate("ventana_principal", u"Definir", None))
        self.menuMaterial.setTitle(QCoreApplication.translate("ventana_principal", u"Material", None))
        self.menuMostrar.setTitle(QCoreApplication.translate("ventana_principal", u"Mostrar", None))
        self.menuReporte.setTitle(QCoreApplication.translate("ventana_principal", u"Reporte", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("ventana_principal", u"Ayuda", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("ventana_principal", u"toolBar", None))
    # retranslateUi

